### ISSUE TITLE
Partition table / ZFS configuration backups

### ISSUE THREAD

**Issue by Sophist-UK** [JoeSchmuck/Multi-Report#3]
@JoeSchmuck Joe

I was wondering whether the script has the ability to save (to a defined location) copies of the partition tables and / or ZFS configurations so that they can be restored if they get corrupted?

I am not quite sure what ZFS configurations could be backed up but SGDISK has the ability to backup the partition table to a file and then restore it.

(Currently trying to help someone else who read somewhere that he should do a `sgdisk -Z` and zapped the partition tables on the two disks he had just added as a 2nd mirror vDev to an existing pool - thus trashing the pool and losing access to the existing data on the 1st vDev. It occurred to me that a backup of the partition table would have made recovery much easier.)

**Comment by JoeSchmuck** [comment]
No sir, Multi-Report does not have that capability.  If you can provide me exact details on the commands for both FreeBSD and Debian, I could generate that portion but who is going to test it to make sure it works?  If I add something like that, I still need to be able to say that it will restore the partition tables without issue.

I use to manipulate partition tables using 'debug' back in the MS-DOS days.  I know there have been some changes since the 1990's.

I think your idea is a good one but someone needs to test it.  And would it restore both partition tables?  I'm under the impression that there are two tables, one at the beginning of the disk and one at the end.  I could be very wrong as well, it has been a long time for me on this topic.

**Comment by Sophist-UK** [comment]
`sgdisk` backup should be relatively easy.

I do not propose an automated restore functionality for the same reasons as the previous issue - you wouldn't want to automate restore unless there was literally 100% chance of doing the correct thing (and that is impossible). But you might want to allow the user to restore based on user input.

I would be happy to test the backup.

I am far less sure about ZFS configuration backup and restore - I will do some research when I have time.

**Comment by JoeSchmuck** [comment]
Hum... Okay.  I added the request to my next build.  I will include it in the next few days and I can forward you the script.  I don't plan to send to out publicly unless there is a driver making me fix something.  I am considering adding it to GitHub then anyone can try as they see fit.  I'll reach out to you in the next day or two.

**Comment by JoeSchmuck** [comment]
I forgot to reach out to you.  I implemented the partition backup a while ago, well it all seems like a long time ago when you get older.  I did not test the recovery of a partition, but it is generated by the script and will go out weekly with the other reports on Monday by default.  Okay, by default the "partition check" is disabled.  This is because on CORE it will need to install (copy) gdisk and sgdisk to the drive and I prefer to let the end user make that choice.  SCALE has the files already.  "partition backup" is enabled by default so if it can run sgdisk, a backup of the partition will be created for each drive and will accompany the TrueNAS configuration backup (default is Monday).

If you give the partition recovery a test, please let me know the outcome.  It would be nice to verify it really works.

-Mark

**Comment by Sophist-UK** [comment]
I just updated - but I didn't spot any options for enabling / disabling partition backups. I will have to wait until Monday to see what I get sent to me.

I won't be testing partition recovery for obvious reasons.

**Comment by JoeSchmuck** [comment]
Sorry about that, I have not added the questions in the configuration file.  Currently it is a manual change in the multi_report_config.txt file.  I will update that today.  I am also working on addressing a problem that people with a lot of drives may have… Getting SMART tests to be configured to run as desired.  One person had over 100 drives, several got missed from the TrueNAS smart self-test routine.  I have a form of it implemented now however after talking to this person, trying to schedule that many drives in 1 week, a bit unrealistic.  The script does it, just not practical.  So I’m slowly working to make it a monthly option.  Select the weeks and days for the weeks to run SMART Long self-tests.
